baseurl: https://shitao5.org/
languageCode: en-us
title: "Shitao Wu | å´è¯—æ¶›"
theme: paged
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "â†©"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
features: ["blog"]
googleAnalytics: "G-TKPT8Q5NBV"

permalinks:
  post: /:year/:month/:slug/

outputs:
  home: [html, rss, json]

author:
  name: "å´è¯—æ¶›"

menu:
  main:
    - name: é¦–é¡µ
      url: "/"
      weight: 1
    - name: å…³äº
      url: "/about/"
      weight: 2
    - name: ï¸æ—¥å¿—
      url: "/posts/"
      weight: 3
    - name: æ€»ç»“
      url: "/summary/"
      weight: 4
    # - name: è¯»è®ºæ–‡
    #   url: "/paper/"
    #   weight: 5
    - name: æœç´¢
      url: "/search/"
      weight: 6
    - name: ğŸ‘‹å¯¹è¯
      url: "/chat/"
      weight: 8
    - name: éšè®°
      url: "/moments/"
      weight: 7
    - name: ğŸ¯è®¢é˜…
      url: "/index.xml"
      weight: 9

params:
  footer: "&copy; [Shitao Wu](/) 2019 - {Year}"
  logo:
    en:
      alt: ä¿®ç‹—
      img: "logo.png"
  customJS:
    - "comment-utils.js"
    - "hash-notes.js"
    - "toggle-notes.js"
    - "post-nav.js"
  githubContentURL: "https://github.com/Shitao5/shitao-blog/edit/main/content/"

  lang:
    edit:
      en: "ç¼–è¾‘"
    license:
      en: "ç‰ˆæƒ"
    search:
      en: "æœç´¢"
    top:
      cn: "ç™»é¡¶"

markup:
  highlight:
    codeFences: true
    style: "github"
  goldmark:
    renderer:
      unsafe: true
    parser:
      autoHeadingIDType: blackfriday
  tableOfContents:
    startLevel: 1

