baseurl: https://shitao5.org/
languageCode: en-us
title: "Shitao Wu | å´è¯—æ¶›"
theme: paged
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "â†©"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
features: ["blog"]

permalinks:
  post: /:year/:month/:slug/

outputs:
  home: [html, rss, json]

menu:
  main:
    - name: é¦–é¡µ
      url: "/"
      weight: 1
    - name: å…³äº
      url: "/about/"
      weight: 2
    - name: ï¸æ—¥å¿—
      url: "/posts/"
      weight: 3
    - name: å‘¨æ€»ç»“
      url: "/summary/"
      weight: 4
    - name: æœç´¢
      url: "/search/"
      weight: 5
    - name: âœ’ï¸å­¦ä¹ 
      url: "https://learn.shitao5.org/"
      weight: 6
    - name: ğŸ¯è®¢é˜…
      url: "/index.xml"
      weight: 7

params:
  footer: "&copy; [Shitao Wu](/) 2019 - {Year}"
  logo:
    en:
      alt: ä¿®ç‹—å¤´åƒ
      img: "logo1.jpg"
  githubContentURL: "https://github.com/Shitao5/shitao-blog/edit/main/content/"

  comments:
    enabled: true
    provider: giscus

    giscus:
      repo: Shitao5/blog-comments
      repoID: R_kgDOHoYglQ
      category: Announcements
      categoryID: DIC_kwDOHoYglc4CV_Ft
      mapping: pathname
      strict: 0
      lightTheme: light
      darkTheme: dark
      reactionsEnabled: 1
      emitMetadata: 0
      inputPosition: bottom
      lang: zh-CN

    lang:
      edit:
        en: "ç¼–è¾‘"
      license:
        en: "ç‰ˆæƒ"
      # subscribe:
      #   cn: "è®¢é˜…"
      search:
        en: "æœç´¢"
      top:
        cn: "ç™»é¡¶"

    markup:
      highlight:
        codeFences: false
      goldmark:
        renderer:
          unsafe: true
        parser:
          autoHeadingIDType: blackfriday
      tableOfContents:
        startLevel: 1
