baseurl: https://shitao.netlify.app/
languageCode: en-us
DefaultContentLanguage: zh-cn
hasCJKLanguage: true
title: "Shitao Wu | å´è¯—æ¶›"
theme: hugo-theme-stack
paginate: 6
googleAnalytics: ''
enableEmoji: true
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/

params:
  mainSections:
    - life
    - read
    - notes
  featuredImageField: image
  rssFullContent: true

  sidebar:
    emoji: ğŸ‘¨â€ğŸ¦¼
    subtitle: "æ°¸è¿œæ†§æ†¬ï¼Œæ°¸è¿œåŠªåŠ›"
    avatar:
      enable: true
      local: true
      src: img/logo.png

  article:
    math: true
    toc: true
    readingTime: true
    license:
        enabled: true
        default: Licensed under CC BY-NC-SA 4.0

  footer:
    since: "2022"
    customText: "Shitao's Blog"

  dateFormat:
    published: 2006-01-02
    lastUpdated: 2006-01-02 15:04 MST

  comments:
    enabled: true
    provider: utterances
    utterances:
      repo: Shitao5/blog-comments
      issueTerm: pathname
      label: ğŸ‘‹

  widgets:
    homepage:
        - type: search
        - type: archives
          params:
              limit: 5
        # - type: categories
        #   params:
        #       limit: 10
        - type: tag-cloud
          params:
              limit: 100
    page:
        - type: toc

  colorScheme:
    toggle: true
    # Available values: auto, light, dark
    default: auto

  imageProcessing:
      cover:
          enabled: true
      content:
          enabled: true

menu:
  main:
    - name: å…³äº
      url: "/about/"
      weight: 1
    - name: ç”Ÿæ´»
      url: "/life/"
      weight: 2
    - name: è¯»ä¹¦
      url: "/read/"
      weight: 3
    - name: ç¬”è®°
      url: "/notes/"
      weight: 4
    - name: ä»–å±±ä¹‹çŸ³
      url: "/others/"
      weight: 5
    # - name: TODO
    #   url: "/todo/"
    #   weight: 5
    # - name: NOT-TODO
    #   url: "/not-todo/"
    #   weight: 6
    - name: RSSè®¢é˜…
      url: "/index.xml"
      weight: 7

  social:
    - identifier: github
      name: GitHub
      url: https://github.com/Shitao5
      weight: 10
      params:
          icon: brand-github
    # - identifier: twitter
    #   name: Twitter
    #   url:
    #   weight: 15
    #   params:
    #       icon: brand-twitter
    - identifier: bilibili
      name: Bilibili
      url: https://space.bilibili.com/646580379
      weight: 20
      params:
          icon: bilibili-line

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100
        # - name: categories
        #   weight: 200

markup:
  goldmark:
    renderer:
      unsafe: yes

  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 1

  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: false
    tabWidth: 4

frontmatter:
  lastmod: [":fileModTime", "lastmod"]

